#!/usr/bin/python

'''

A dictionary of supported MHCII

'''
# import required libraries
from collections import defaultdict

mhciibeta_trim = defaultdict(dict)
mhciibeta_trim['mhciibeta']='DTRPRFLEQVKHECHFFNGTERVRFLDRYFYHQEEYVRFDSDVGEYRAVTELGRPDAEYWNSQKDLLEQRRAAVDTYCRHNYGVVESFTVQRRVYPEVTVYPAKTQPLQHHNLLVCSVNGFYPGSIEVRWFRNGQEEKTGVVSTGLIQNGDWTFQTLVMLETVPRSGEVYTCQVEHPSLTSPLTVEWRA'

